apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: jlocamuz/next-js-agus-garcia:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nextjs-env-secrets
                  key: DATABASE_URL
            - name: SECRET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nextjs-env-secrets
                  key: SECRET_API_KEY
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextjs-env-secrets
                  key: ADMIN_PASSWORD
